server:
  port: 8080

#DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devbase?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver